# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=15)),
                ('gender', models.BinaryField()),
                ('user_token', models.CharField(max_length=20)),
            ],
        ),
    ]
