# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_user_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='food_id',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
