# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180306_0126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='food_recipe',
            new_name='user_recipe',
        ),
    ]
