# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20180306_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('ingr_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ingr_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='peymane',
            fields=[
                ('title', models.CharField(max_length=20)),
                ('peymane_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='recipe_ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ingredient')),
                ('peymane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.peymane')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.recipe')),
            ],
        ),
    ]
