# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_ingredient_peymane_recipe_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='food_image',
            field=models.ImageField(blank=True, upload_to='recipe_images'),
        ),
    ]
