# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-11 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
